@extends('layouts.app')

@section('title', 'Employee Management Guide')

@section('content')
<div class="container-fluid px-0">
    <div class="row mb-4">
        <div class="col-12">
            <div class="card stat-card border-0 shadow-sm">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <a href="{{ route('help.index') }}" class="btn btn-outline-secondary me-3">
                            <i class="fas fa-arrow-left"></i>
                        </a>
                        <div>
                            <h4 class="mb-2">
                                <i class="fas fa-users text-success me-2"></i>
                                Employee Management Guide
                            </h4>
                            <p class="text-muted mb-0">Learn how to manage employee data effectively</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <!-- Adding Employees -->
            <div class="card stat-card mb-4">
                <div class="card-body">
                    <h5 class="mb-3">
                        <span class="badge bg-success me-2">1</span>
                        Adding New Employees
                    </h5>
                    <div class="ms-4">
                        <p class="text-muted">To add a new employee to the system:</p>
                        <ol class="text-muted">
                            <li>Navigate to the <strong>Employees</strong> menu in the sidebar</li>
                            <li>Click the <span class="badge bg-primary">Add New Employee</span> button</li>
                            <li>Fill in the employee details:
                                <ul class="mt-2">
                                    <li><strong>Name</strong> - Employee's full name</li>
                                    <li><strong>Email</strong> - Valid email address</li>
                                    <li><strong>Position</strong> - Job title/position</li>
                                    <li><strong>Department</strong> - Select from available departments</li>
                                    <li><strong>Phone</strong> - Contact number (optional)</li>
                                    <li><strong>Address</strong> - Residential address (optional)</li>
                                    <li><strong>Photo</strong> - Upload profile picture (optional)</li>
                                </ul>
                            </li>
                            <li>Click <span class="badge bg-success">Save Employee</span> to complete</li>
                        </ol>
                        <div class="alert alert-info mt-3">
                            <i class="fas fa-info-circle me-2"></i>
                            Employee ID will be automatically generated by the system.
                        </div>
                    </div>
                </div>
            </div>

            <!-- Editing Employees -->
            <div class="card stat-card mb-4">
                <div class="card-body">
                    <h5 class="mb-3">
                        <span class="badge bg-warning me-2">2</span>
                        Editing Employee Information
                    </h5>
                    <div class="ms-4">
                        <p class="text-muted">To update employee details:</p>
                        <ol class="text-muted">
                            <li>Go to the <strong>Employees</strong> list</li>
                            <li>Find the employee you want to edit</li>
                            <li>Click the <i class="fas fa-edit text-warning"></i> edit button</li>
                            <li>Update the necessary information</li>
                            <li>Click <span class="badge bg-primary">Update Employee</span> to save changes</li>
                        </ol>
                    </div>
                </div>
            </div>

            <!-- Deleting Employees -->
            <div class="card stat-card mb-4">
                <div class="card-body">
                    <h5 class="mb-3">
                        <span class="badge bg-danger me-2">3</span>
                        Deleting Employees
                    </h5>
                    <div class="ms-4">
                        <p class="text-muted">To remove an employee from the system:</p>
                        <ol class="text-muted">
                            <li>Navigate to the <strong>Employees</strong> list</li>
                            <li>Find the employee you want to remove</li>
                            <li>Click the <i class="fas fa-trash text-danger"></i> delete button</li>
                            <li>Confirm the deletion when prompted</li>
                        </ol>
                        <div class="alert alert-warning mt-3">
                            <i class="fas fa-exclamation-triangle me-2"></i>
                            <strong>Warning:</strong> Deleting an employee will also remove all their attendance records. Consider deactivating instead of deleting.
                        </div>
                    </div>
                </div>
            </div>

            <!-- Employee Status -->
            <div class="card stat-card mb-4">
                <div class="card-body">
                    <h5 class="mb-3">
                        <span class="badge bg-info me-2">4</span>
                        Employee Status
                    </h5>
                    <div class="ms-4">
                        <p class="text-muted">Employees can have two statuses:</p>
                        <ul class="text-muted">
                            <li><span class="badge bg-success">Active</span> - Employee can record attendance</li>
                            <li><span class="badge bg-danger">Inactive</span> - Employee cannot record attendance</li>
                        </ul>
                        <p class="text-muted">Use the status toggle to activate or deactivate employees without deleting their data.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <!-- Quick Tips -->
            <div class="card stat-card mb-4">
                <div class="card-header bg-white">
                    <h6 class="mb-0">Quick Tips</h6>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled">
                        <li class="mb-3">
                            <i class="fas fa-check-circle text-success me-2"></i>
                            Upload employee photos for easy identification
                        </li>
                        <li class="mb-3">
                            <i class="fas fa-check-circle text-success me-2"></i>
                            Use departments to organize employees
                        </li>
                        <li class="mb-3">
                            <i class="fas fa-check-circle text-success me-2"></i>
                            Keep employee information up to date
                        </li>
                        <li class="mb-3">
                            <i class="fas fa-check-circle text-success me-2"></i>
                            Deactivate instead of delete to preserve history
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Related Articles -->
            <div class="card stat-card">
                <div class="card-header bg-white">
                    <h6 class="mb-0">Related Articles</h6>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled">
                        <li class="mb-2">
                            <a href="{{ route('help.getting-started') }}" class="text-decoration-none">
                                <i class="fas fa-arrow-right text-primary me-2"></i>
                                Getting Started
                            </a>
                        </li>
                        <li class="mb-2">
                            <a href="{{ route('help.attendance-guide') }}" class="text-decoration-none">
                                <i class="fas fa-arrow-right text-primary me-2"></i>
                                Attendance Guide
                            </a>
                        </li>
                        <li class="mb-2">
                            <a href="{{ route('help.reports-guide') }}" class="text-decoration-none">
                                <i class="fas fa-arrow-right text-primary me-2"></i>
                                Reports Guide
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection